language: node_js
node_js: 
    - "stable"
services:
    - docker
before_install:
    - docker build -t ronydebnath/react-app -f Dockerfile.dev .
script:
    - docker run ronydebnath/react-app npm run test npm run test -- --watchAll=false
    # alternatively we can run the below test command also to test our code
    # docker run -e CI=true ronydebnath/react-app npm run test