FROM node:alpine

WORKDIR '/app'

COPY package*.json .

RUN npm install

COPY . .

# Uses port which is used by the actual application
# EXPOSE 3000
 
# Finally runs the application
CMD [ "npm", "run", "start" ]

# build this image with docker build -f Dockerfile.dev .
# run: docker run -it -p 3000:3000 <imageId>
# run: docker run -it -p 3000:3000 -v $(pwd):/app -v /app/node_modules <imageId>   // this will reload the file changes automatically